### PR TITLE
Changed the importlib functions that caused relative import errors

### PR DESCRIPTION
**Pull request by jgrueb**
I tried to solve to problem that some guys had in 

https://github.com/openassistant/oa-core/issues/12

To solve this issue, I just changed two of the importlib functions slightly. Hope this helps =)

### CODE REVIEW

**Comment by joshuashort** [comment]
**Thank you**!

(Never mind, just saw your comment on #12) Were you experiencing the same error, too? I've tried this in my environment, and it seems to still work, but I can't speak for those affected by #12.

Regardless, this looks like a good change.

**Comment by jgrueb** [comment]
Allright! Would be nice if this would also work for the others involved.

**Comment by ckheli** [comment]
Hello.
Did the possible, but get this stuff
$ python -m oa
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ckheli/ai/oa-core-master/oa/__main__.py", line 10, in <module>
    from oa import core
  File "oa/core/__init__.py", line 11, in <module>
    import queue
ImportError: No module named queue

Don't know what to do

**Comment by joshuashort** [comment]
The short answer: use Python 3.

**Comment by ckheli** [comment]
I think i have launced with all pythons that i have, but i retry.
Thank you very much, i will keep update.

**Comment by ckheli** [comment]
Thank you.
In the end i was able to run OA!
I tried yesterday different versions of python that i had, but i don't know how, with python3 and some about "queue" calling editing in the files, i was able to go over the error and the console opens. I have had other issues with soundcard, alsamixer, sound output "dummy" and no input, but i was able to adjust it and it works. I had to install alot of stuff and sphinx along with pocketsphinx (which i see usr/local/lib are dubbed for them for python 2.7 and 3.x).
Now im going to work to add other languages, as i supposed, and as you confirmed in another post, it's pocketshpinx matter, of the language recognition, and just to attach it to OA, but it looks not so easy in the immediate.
Great project OA, very great, and very great possibility to have it on local instead of on a cloud.
Looking for collaborate, if i can contribute, and looking for tensorflow and other ai/ml/dl joining, it would be the greatest ai assistant ever; if it can learn, learning from trials and errors, and if we can teach it, expand it's brain, and that it is able to write alone python code of itself, well.. great stuff ever. Thank you and compliments for your work.

**Comment by joshuashort** [comment]
That's great news! Sounds like you really dug in and got your hands dirty -- the 'queue' thing is just one of many differences between 2.x and 3.x; it's a bit hard to support 2 *and* 3, so I've opted for 3. 2 is on its way out (and has been for a while), but it's still going to take some time, but that's the future.

It's going to depend on which distro/OS/etc, you're using, but the commands `pip3`, `python3`, and packages like `python3-` in your package manager are what you might need to look for. The 'plain' version of these might be using a 2.x version on your system.

I wish it was easier, but this is kind of pre-alpha and I haven't had much personal time/motivation/energy.. I'm hoping I can change that in the next month. But I'm always happy to chat and address issues. You seem engaged and interested, and I'd like to support that.

There are some design changes that'll be needed to make swapping languages easy/supported. For now, you're basically hacking on the internals. I'm eager to hear from you about how it goes.

Thanks for the kind words -- it's a hard problem; and thanks for the patience and interest. I want it to be an easy, local-first platform for exploring those things you're interested in making it do! Collaboration and contribution is needed -- it's a construction zone, so watch your head and keep an open mind :)

**Comment by ckheli** [comment]
Thank you too for what you write.

>> I haven't had much personal time/motivation/energy..  
Who have? :D 

>>I haven't had much personal time/motivation/energy.. 
I'm actually motivating you :)
The project itself motivate you
--
Things was going smooth until a point; after which i installed anaconda3 and things looks like messed up now, don't know what it's happening; i'm almost new to python, less new to linux/unix and come from C/C++ so it would require some personal effort for me to go deep in.

This framework is very nice and interesting, yet early stage, but it is nice, definitely. 
Easy is good, but some things must always be kept "nerdy" up to a certain percentage. 

I think anaconda messed up with libraries and/or envorionment: now the oa cannot see pocketshipnx again, and other errors. Will see if i can hack the debug myself, or ask your help (surely) :D

**Comment by ckheli** [comment]
Thank you too for what you write.

>> I haven't had much personal time/motivation/energy..  

Who have? :D 

>>I haven't had much personal time/motivation/energy.. 

I'm actually motivating you :)
The project itself motivate you

Things was going smooth until a point; after which i installed anaconda3 and things looks like messed up now, don't know what it's happening; i'm almost new to python, less new to linux/unix and come from C/C++ so it would require some personal effort for me to go deep in.

This framework is very nice and interesting, yet early stage, but it is nice, definitely. 
Easy is good, but some things must always be kept "nerdy" up to a certain percentage. 

I think anaconda messed up with libraries and/or envorionment: now the oa cannot see pocketshipnx again, and other errors. Will see if i can hack the debug myself, or ask your help (surely) :D

**Comment by ckheli** [comment]
Update: solved. was just enough to deactivate anaconda.
evidently i was lunching the program under the virtual env, with messing with all the libraries

**Pull request merged**
